# Generated by Django 5.1.7 on 2025-04-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_movie_created_at_movie_is_oscar_contender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
