# Generated by Django 5.1.7 on 2025-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_movie_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_coming_next_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_coming_this_month',
            field=models.BooleanField(default=False),
        ),
    ]
